MERGE (p:Project {id: 'project:orchestrator-agent-001', name: 'agentic-builderX'})
MERGE (w:Workflow {id: 'bootstrap-orchestrator-001', name: 'Bootstrap Orchestrator', status: 'complete'})
MERGE (a:Agent {id: 'project-execution-agent', name: 'Project Execution Agent', status: 'active', version: '1.0.0'})
MERGE (m:ApplicationFunctionality {id: 'agent-memory', name: 'Agent Memory', status: 'bootstrapped'})
MERGE (g:ApplicationFunctionality {id: 'neo4j-graph', name: 'Neo4j Graph Artifacts', status: 'ready'})
MERGE (v:VectorMemoryProvider {id: 'vector-memory', provider: 'chroma_local_generated', status: 'pending_install'})
MERGE (d:D3Page {id: 'agentic-system-d3', path: 'agentic-system/d3/index.html', status: 'ready'})
MERGE (p)-[:CONTAINS]->(w)
MERGE (w)-[:ASSIGNED_TO]->(a)
MERGE (a)-[:OWNS]->(m)
MERGE (a)-[:OWNS]->(g)
MERGE (a)-[:OWNS]->(v)
MERGE (g)-[:VISUALIZED_BY]->(d)
MERGE (v)-[:VISUALIZED_BY]->(d);
