MERGE (a:Agent {id: 'builderx-fullstack-agent', name: 'BuilderX Fullstack Agent', status: 'active'})
MERGE (frontend:Cluster {id: 'frontend_control_surface', name: 'Frontend Control Surface', risk_level: 'medium'})
MERGE (backend:Cluster {id: 'backend_generation_api', name: 'Backend Generation API', risk_level: 'high'})
MERGE (mcp:Cluster {id: 'mcp_generation_endpoint', name: 'MCP Generation Endpoint', risk_level: 'high'})
MERGE (runtime:Cluster {id: 'generated_site_runtime', name: 'Generated Site Runtime', risk_level: 'medium'})
MERGE (docker:Cluster {id: 'container_orchestration', name: 'Container Orchestration', risk_level: 'medium'})
MERGE (a)-[:OWNS]->(frontend)
MERGE (a)-[:OWNS]->(backend)
MERGE (a)-[:OWNS]->(mcp)
MERGE (a)-[:OWNS]->(runtime)
MERGE (a)-[:OWNS]->(docker)
MERGE (frontend)-[:DEPENDS_ON]->(backend)
MERGE (frontend)-[:DEPENDS_ON]->(runtime)
MERGE (mcp)-[:DEPENDS_ON]->(backend)
MERGE (backend)-[:WRITES]->(runtime)
MERGE (docker)-[:CONTAINS]->(frontend)
MERGE (docker)-[:CONTAINS]->(backend)
MERGE (docker)-[:CONTAINS]->(runtime);
