CREATE CONSTRAINT project_id IF NOT EXISTS FOR (n:Project) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT workflow_id IF NOT EXISTS FOR (n:Workflow) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT task_id IF NOT EXISTS FOR (n:Task) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT agent_id IF NOT EXISTS FOR (n:Agent) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT functionality_id IF NOT EXISTS FOR (n:ApplicationFunctionality) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT prompt_id IF NOT EXISTS FOR (n:PromptRecord) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT knowledge_id IF NOT EXISTS FOR (n:KnowledgeEntry) REQUIRE n.id IS UNIQUE;
