// Generated by Agentic BuilderX project-agent registry.
// This file keeps managed app projects related to their project-scoped agents.
MERGE (:Agent {id: 'builderx-fullstack-agent', name: 'BuilderX Fullstack Agent', role: 'global-orchestrator', status: 'active'})
MERGE (:Agent {id: 'builderx-independent-reviewer', name: 'BuilderX Independent Reviewer', role: 'reviewer', status: 'available', read_only: true})
MATCH (o:Agent {id: 'builderx-fullstack-agent'}), (r:Agent {id: 'builderx-independent-reviewer'}) MERGE (o)-[:MAY_REQUEST_REVIEW_FROM {adaptive: true}]->(r)

MERGE (p:Project {id: 'project:porny-RuQJlr'})
SET p.name = "porny", p.folder_name = "porny", p.workspace_dir = "/workspace/money/apps/porny", p.port = 5301
MERGE (a:Agent {id: "porny-orchestrator-agent"})
SET a.name = "Porny Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "porny-RuQJlr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "porny-qagent-controller"})
SET a.name = "Porny QAgent Controller", a.role = "qagent-controller", a.project_id = "porny-RuQJlr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "porny-ui-composition-agent"})
SET a.name = "Porny UI Composition Agent", a.role = "ui-composition", a.project_id = "porny-RuQJlr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "porny-content-data-agent"})
SET a.name = "Porny Content Data Agent", a.role = "content-data", a.project_id = "porny-RuQJlr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "porny-runtime-packaging-agent"})
SET a.name = "Porny Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "porny-RuQJlr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "builderx-fullstack-agent"}), (b:Agent {id: "porny-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:porny-RuQJlr'}), (a:Agent {id: "porny-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "porny-orchestrator-agent"}), (b:Agent {id: "porny-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "porny-orchestrator-agent"}), (b:Agent {id: "porny-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "porny-orchestrator-agent"}), (b:Agent {id: "porny-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "porny-orchestrator-agent"}), (b:Agent {id: "porny-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:ramo-Fbo8Fr'})
SET p.name = "Ramo", p.folder_name = "ramo", p.workspace_dir = "/workspace/money/apps/ramo", p.port = 5300
MERGE (a:Agent {id: "ramo-orchestrator-agent"})
SET a.name = "Ramo Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "ramo-Fbo8Fr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "ramo-qagent-controller"})
SET a.name = "Ramo QAgent Controller", a.role = "qagent-controller", a.project_id = "ramo-Fbo8Fr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "ramo-ui-composition-agent"})
SET a.name = "Ramo UI Composition Agent", a.role = "ui-composition", a.project_id = "ramo-Fbo8Fr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "ramo-content-data-agent"})
SET a.name = "Ramo Content Data Agent", a.role = "content-data", a.project_id = "ramo-Fbo8Fr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "ramo-runtime-packaging-agent"})
SET a.name = "Ramo Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "ramo-Fbo8Fr", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (a:Agent {id: "builderx-fullstack-agent"}), (b:Agent {id: "ramo-orchestrator-agent"}) MERGE (a)-[:RUNTIME_DELEGATES_TO]->(b)
MATCH (p:Project {id: 'project:ramo-Fbo8Fr'}), (a:Agent {id: "ramo-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "ramo-orchestrator-agent"}), (b:Agent {id: "ramo-qagent-controller"}) MERGE (a)-[:USES_QAGENT_CONTROLLER]->(b)
MATCH (a:Agent {id: "ramo-orchestrator-agent"}), (b:Agent {id: "ramo-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "ramo-orchestrator-agent"}), (b:Agent {id: "ramo-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "ramo-orchestrator-agent"}), (b:Agent {id: "ramo-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

