// Generated by Agentic BuilderX project-agent registry.
// This file keeps managed app projects related to their project-scoped agents.

MERGE (p:Project {id: 'project:geofinderx-2yFsDY'})
SET p.name = "GeoFinderX", p.folder_name = "geofinderx", p.workspace_dir = "/workspace/money/apps/geofinderx", p.port = 5300
MERGE (a:Agent {id: "geofinderx-orchestrator-agent"})
SET a.name = "Geofinderx Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "geofinderx-2yFsDY", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "geofinderx-ui-composition-agent"})
SET a.name = "Geofinderx UI Composition Agent", a.role = "ui-composition", a.project_id = "geofinderx-2yFsDY", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "geofinderx-content-data-agent"})
SET a.name = "Geofinderx Content Data Agent", a.role = "content-data", a.project_id = "geofinderx-2yFsDY", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "geofinderx-runtime-packaging-agent"})
SET a.name = "Geofinderx Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "geofinderx-2yFsDY", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (p:Project {id: 'project:geofinderx-2yFsDY'}), (a:Agent {id: "geofinderx-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "geofinderx-orchestrator-agent"}), (b:Agent {id: "geofinderx-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "geofinderx-orchestrator-agent"}), (b:Agent {id: "geofinderx-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "geofinderx-orchestrator-agent"}), (b:Agent {id: "geofinderx-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

MERGE (p:Project {id: 'project:mapex-M6rGkR'})
SET p.name = "mapEx", p.folder_name = "mapex", p.workspace_dir = "/workspace/money/mapex", p.port = 5301
MERGE (a:Agent {id: "mapex-orchestrator-agent"})
SET a.name = "Mapex Orchestrator Agent", a.role = "project-orchestrator", a.project_id = "mapex-M6rGkR", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mapex-ui-composition-agent"})
SET a.name = "Mapex UI Composition Agent", a.role = "ui-composition", a.project_id = "mapex-M6rGkR", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mapex-content-data-agent"})
SET a.name = "Mapex Content Data Agent", a.role = "content-data", a.project_id = "mapex-M6rGkR", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MERGE (a:Agent {id: "mapex-runtime-packaging-agent"})
SET a.name = "Mapex Runtime Packaging Agent", a.role = "runtime-packaging", a.project_id = "mapex-M6rGkR", a.status = 'active'
MERGE (p)-[:OWNS]->(a)
MATCH (p:Project {id: 'project:mapex-M6rGkR'}), (a:Agent {id: "mapex-orchestrator-agent"}) MERGE (p)-[:HAS_ORCHESTRATOR]->(a)
MATCH (a:Agent {id: "mapex-orchestrator-agent"}), (b:Agent {id: "mapex-ui-composition-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "mapex-orchestrator-agent"}), (b:Agent {id: "mapex-content-data-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)
MATCH (a:Agent {id: "mapex-orchestrator-agent"}), (b:Agent {id: "mapex-runtime-packaging-agent"}) MERGE (a)-[:DELEGATES_TO]->(b)

