MERGE (p:Project {id: 'project:agentic-builderX', name: 'agentic-builderX'})
MERGE (w:Workflow {id: 'builderx-large-001', name: 'Build Agentic BuilderX', status: 'implemented'})
MERGE (p)-[:CONTAINS]->(w)
MERGE (frontend:Service {id: 'service:frontend', name: 'frontend', status: 'implemented'})
MERGE (backend:Service {id: 'service:backend', name: 'backend', status: 'implemented'})
MERGE (generated:Service {id: 'service:generated-site', name: 'generated-site', status: 'implemented'})
MERGE (mcp:Endpoint {id: 'endpoint:mcp', path: 'POST /mcp', status: 'implemented'})
MERGE (backend)-[:EXPOSES]->(mcp)
MERGE (frontend)-[:CALLS]->(backend)
MERGE (frontend)-[:CONSUMES]->(generated)
MERGE (backend)-[:WRITES]->(generated)
MERGE (p)-[:CONTAINS]->(frontend)
MERGE (p)-[:CONTAINS]->(backend)
MERGE (p)-[:CONTAINS]->(generated);
