import crypto from "node:crypto";
import path from "node:path";
import fs from "fs-extra";
import { nanoid } from "nanoid";

const generatedDir = process.env.GENERATED_SITE_DIR || path.resolve(process.cwd(), "../generated-site");
const generatedSourceDir = path.join(generatedDir, "src", "generated");

function cleanInstruction(value) {
  return String(value || "")
    .replace(/[<>]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 8000);
}

function titleCase(value) {
  return String(value || "digital product")
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join(" ");
}

function isBagBusiness(request) {
  const text = `${request?.topic || ""} ${request?.sourceInstruction || ""}`.toLowerCase();
  return text.includes("bag") || text.includes("handbag") || text.includes("luggage") || text.includes("backpack");
}

function buildCommerceModel(request) {
  const bagBusiness = isBagBusiness(request);
  if (bagBusiness) {
    return {
      brand: "Atelier Carry",
      eyebrow: "Generated commerce experience",
      headline: "Premium bags for workdays, weekends, and everything in motion",
      subhead:
        "A refined bag business storefront with bestsellers, material storytelling, trust cues, and a conversion-ready product journey.",
      cta: "Shop signature bags",
      secondaryCta: "Explore materials",
      stats: [
        { label: "Signature styles", value: "24" },
        { label: "Avg. rating", value: "4.9" },
        { label: "Ships in", value: "48h" }
      ],
      products: [
        {
          name: "The Metro Tote",
          price: "$168",
          tag: "Work essential",
          description: "Structured vegan leather tote with padded laptop sleeve and hidden zip pocket."
        },
        {
          name: "Aero Crossbody",
          price: "$96",
          tag: "Everyday carry",
          description: "Compact hands-free profile with brushed hardware and adjustable woven strap."
        },
        {
          name: "Weekender 42",
          price: "$220",
          tag: "Travel ready",
          description: "Cabin-friendly duffle with shoe garage, trolley sleeve, and weather-resistant canvas."
        }
      ],
      materials: ["Italian recycled nylon", "Plant-based leather", "Solid brass hardware", "Organic cotton lining"],
      workflow: ["Choose your silhouette", "Pick material and color", "Add monogramming", "Ship with carbon-neutral delivery"]
    };
  }

  const topic = titleCase(request?.topic || "product");
  return {
    brand: `${topic} Command Center`,
    eyebrow: "Generated by Agentic BuilderX",
    headline: `${topic} experiences designed for teams that move fast`,
    subhead: cleanInstruction(request?.sourceInstruction || request?.objective),
    cta: `Launch ${topic}`,
    secondaryCta: "Review workflow",
    stats: [
      { label: "Build velocity", value: "4.8x" },
      { label: "Conversion lift", value: "31%" },
      { label: "Design score", value: "A+" }
    ],
    products: [
      {
        name: "Strategy-led structure",
        price: "A+",
        tag: "Positioning",
        description: "Clear outcomes, confident hierarchy, and scan-friendly sections."
      },
      {
        name: "Runtime-ready polish",
        price: "Live",
        tag: "Preview",
        description: "Spacing, contrast, and calls to action prepared for real-time review."
      },
      {
        name: "Composable sections",
        price: "Modular",
        tag: "System",
        description: "Blocks can evolve into pricing, onboarding, demos, or workflow pages."
      }
    ],
    materials: ["Responsive layout", "Professional typography", "Accessible contrast", "Reusable React modules"],
    workflow: ["Capture intent", "Plan file operations", "Apply generated source", "Restart preview container"]
  };
}

function catalogDataSource(model) {
  return `export const catalog = ${JSON.stringify(model, null, 2)};
`;
}

function pageSource(instructionHash) {
  return `import { catalog } from "./catalogData.js";

export const generatedMetadata = {
  instructionHash: ${JSON.stringify(instructionHash)},
  generatedAt: ${JSON.stringify(new Date().toISOString())}
};

export default function GeneratedPage() {
  return (
    <main className="generated-page">
      <section className="hero">
        <nav className="nav">
          <strong>{catalog.brand}</strong>
          <div>
            <a href="#catalog">Catalog</a>
            <a href="#materials">Materials</a>
            <a href="#workflow">Experience</a>
          </div>
        </nav>
        <div className="hero-grid">
          <div className="hero-copy">
            <span>{catalog.eyebrow}</span>
            <h1>{catalog.headline}</h1>
            <p>{catalog.subhead}</p>
            <div className="hero-actions">
              <a className="primary" href="#catalog">{catalog.cta}</a>
              <a className="secondary" href="#materials">{catalog.secondaryCta}</a>
            </div>
          </div>
          <div className="insight-panel">
            <h2>Storefront snapshot</h2>
            <p>Generated through Codex workflow file operations and refreshed in its preview container.</p>
            <div className="panel-grid">
              {catalog.stats.map((stat) => (
                <div key={stat.label}>
                  <strong>{stat.value}</strong>
                  <span>{stat.label}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="catalog-section" id="catalog">
        <div className="section-intro">
          <span>Generated catalog</span>
          <h2>Merchandised for fast browsing and confident checkout.</h2>
        </div>
        <div className="product-grid">
          {catalog.products.map((product) => (
            <article key={product.name} className="product-card">
              <div className="product-visual">
                <span>{product.tag}</span>
              </div>
              <div>
                <h3>{product.name}</h3>
                <strong>{product.price}</strong>
                <p>{product.description}</p>
              </div>
            </article>
          ))}
        </div>
      </section>

      <section className="materials" id="materials">
        <div>
          <span>Material story</span>
          <h2>Every detail supports trust, durability, and premium positioning.</h2>
        </div>
        <ul>
          {catalog.materials.map((item) => (
            <li key={item}>{item}</li>
          ))}
        </ul>
      </section>

      <section className="workflow" id="workflow">
        <div>
          <span>Buying experience</span>
          <h2>Simple enough to browse, structured enough to scale.</h2>
        </div>
        <ol>
          {catalog.workflow.map((step, index) => (
            <li key={step}>
              <strong>{String(index + 1).padStart(2, "0")}</strong>
              <span>{step}</span>
            </li>
          ))}
        </ol>
      </section>

      <section className="launch">
        <h2>{catalog.cta}</h2>
        <p>Regenerate from Agentic BuilderX to add, modify, or delete files in this generated app.</p>
      </section>
    </main>
  );
}
`;
}

function cssSource() {
  return `:root {
  color: #142033;
  background: #f6f7fb;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

* { box-sizing: border-box; }
body { margin: 0; }
a { color: inherit; text-decoration: none; }

.generated-page {
  min-height: 100vh;
  background:
    linear-gradient(130deg, rgba(15, 118, 110, 0.12), transparent 38%),
    linear-gradient(155deg, rgba(37, 99, 235, 0.12), transparent 44%),
    #f6f7fb;
}

.hero {
  min-height: 88vh;
  padding: 28px;
  display: grid;
  grid-template-rows: auto 1fr;
}

.nav {
  max-width: 1180px;
  width: 100%;
  margin: 0 auto;
  height: 60px;
  border: 1px solid #d8e1ee;
  border-radius: 8px;
  padding: 0 18px;
  background: rgba(255, 255, 255, 0.88);
  display: flex;
  align-items: center;
  justify-content: space-between;
  backdrop-filter: blur(16px);
}

.nav div { display: flex; gap: 18px; color: #526174; font-size: 14px; }

.hero-grid {
  max-width: 1180px;
  width: 100%;
  margin: 0 auto;
  display: grid;
  grid-template-columns: minmax(0, 1.08fr) minmax(320px, 0.92fr);
  gap: 36px;
  align-items: center;
}

.hero-copy span,
.section-intro span,
.materials span,
.workflow span {
  color: #0f766e;
  font-weight: 800;
  text-transform: uppercase;
  font-size: 12px;
  letter-spacing: 0.08em;
}

.hero-copy h1 {
  margin: 14px 0 18px;
  font-size: clamp(44px, 7vw, 82px);
  line-height: 0.96;
  letter-spacing: 0;
}

.hero-copy p {
  max-width: 690px;
  color: #536174;
  font-size: 20px;
  line-height: 1.55;
}

.hero-actions { margin-top: 28px; display: flex; flex-wrap: wrap; gap: 12px; }

.primary,
.secondary {
  min-height: 48px;
  padding: 0 18px;
  display: inline-flex;
  align-items: center;
  border-radius: 8px;
  font-weight: 800;
}

.primary { color: #fff; background: #0f766e; box-shadow: 0 16px 32px rgba(15, 118, 110, 0.22); }
.secondary { border: 1px solid #d8e1ee; background: #fff; }

.insight-panel,
.product-card,
.materials,
.workflow {
  border: 1px solid #d8e1ee;
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.92);
  box-shadow: 0 24px 70px rgba(15, 23, 42, 0.1);
}

.insight-panel { padding: 24px; }
.insight-panel h2 { margin: 0 0 8px; font-size: 24px; }
.insight-panel p { color: #64748b; margin: 0; line-height: 1.6; }

.panel-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-top: 24px; }
.panel-grid div { border: 1px solid #d8e1ee; border-radius: 8px; background: #fff; padding: 14px; }
.panel-grid strong { display: block; font-size: 26px; }
.panel-grid span { color: #64748b; font-size: 12px; }

.catalog-section {
  max-width: 1180px;
  margin: 0 auto;
  padding: 20px 28px 72px;
}

.section-intro {
  max-width: 760px;
  margin-bottom: 18px;
}

.section-intro h2,
.materials h2,
.workflow h2 {
  margin: 10px 0 0;
  font-size: 32px;
  line-height: 1.15;
}

.product-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
}

.product-card {
  overflow: hidden;
}

.product-visual {
  min-height: 180px;
  background:
    radial-gradient(circle at 30% 20%, rgba(255,255,255,.75), transparent 28%),
    linear-gradient(135deg, #172033, #0f766e);
  display: flex;
  align-items: flex-end;
  padding: 16px;
  color: #fff;
  font-weight: 800;
}

.product-card div:last-child { padding: 18px; }
.product-card h3 { margin: 0 0 8px; font-size: 22px; }
.product-card strong { color: #0f766e; }
.product-card p { color: #64748b; line-height: 1.55; margin: 10px 0 0; }

.materials,
.workflow {
  max-width: 1124px;
  margin: 0 auto 26px;
  padding: 28px;
  display: grid;
  grid-template-columns: 0.9fr 1.1fr;
  gap: 28px;
}

.materials ul,
.workflow ol {
  margin: 0;
  padding: 0;
  list-style: none;
  display: grid;
  gap: 10px;
}

.materials li,
.workflow li {
  min-height: 56px;
  padding: 12px;
  border-radius: 8px;
  background: #f8fafc;
  display: flex;
  align-items: center;
  gap: 12px;
}

.workflow li strong { color: #2563eb; }

.launch {
  max-width: 1180px;
  margin: 0 auto;
  padding: 42px 28px 72px;
  text-align: center;
}

.launch h2 { margin: 0 0 10px; font-size: 42px; }
.launch p { margin: 0 auto; max-width: 620px; color: #64748b; line-height: 1.6; }

@media (max-width: 900px) {
  .hero-grid,
  .materials,
  .workflow,
  .product-grid {
    grid-template-columns: 1fr;
  }

  .hero { padding: 16px; }
  .nav div { display: none; }
}
`;
}

function readmeSource(request, operations) {
  return `# Generated App

This app was generated by Agentic BuilderX through the Codex workflow file-operation runtime.

## Orchestrator Objective

${request.objective}

## File Operations

${operations.map((operation) => `- ${operation.action}: \`${operation.path}\` - ${operation.reason}`).join("\n")}
`;
}

function buildOperations(request, buildId, instructionHash) {
  const model = buildCommerceModel(request);
  const operations = request.fileOperations || [];
  const contentByPath = new Map([
    ["src/generated/generatedPage.jsx", pageSource(instructionHash)],
    ["src/generated/generatedPage.css", cssSource()],
    ["src/generated/catalogData.js", catalogDataSource(model)],
    [
      "src/generated/metadata.json",
      JSON.stringify(
        {
          buildId,
          instructionHash,
          generatedAt: new Date().toISOString(),
          title: model.brand,
          orchestrated: {
            pageType: request.pageType,
            topic: request.topic,
            sections: request.sections
          },
          fileOperations: operations
        },
        null,
        2
      )
    ],
    ["src/generated/README.generated.md", readmeSource(request, operations)]
  ]);

  const priorityByPath = new Map([
    ["src/generated/catalogData.js", 1],
    ["src/generated/metadata.json", 2],
    ["src/generated/README.generated.md", 3],
    ["src/generated/generatedPage.jsx", 4],
    ["src/generated/generatedPage.css", 5],
    ["src/generated/deprecatedGeneratedPage.jsx", 6]
  ]);

  return operations
    .map((operation, index) => ({
      ...operation,
      index,
      absolutePath: path.join(generatedDir, operation.path),
      content: contentByPath.get(operation.path) || ""
    }))
    .sort((a, b) => (priorityByPath.get(a.path) || 50) - (priorityByPath.get(b.path) || 50) || a.index - b.index);
}

async function applyOperation(operation) {
  const existedBefore = await fs.pathExists(operation.absolutePath);
  if (operation.action === "delete") {
    await fs.remove(operation.absolutePath);
    return { existedBefore, bytesWritten: 0 };
  }
  await fs.ensureDir(path.dirname(operation.absolutePath));
  await fs.writeFile(operation.absolutePath, operation.content);
  return { existedBefore, bytesWritten: Buffer.byteLength(operation.content || "", "utf8") };
}

export async function generateWebpage(orchestratedRequest, options = {}) {
  const emit = typeof options.emit === "function" ? options.emit : () => {};
  const request =
    typeof orchestratedRequest === "string"
      ? {
          sourceInstruction: orchestratedRequest,
          objective: orchestratedRequest,
          topic: "digital product",
          pageType: "professional_landing_page",
          sections: ["hero", "proof", "workflow", "cta"],
          fileOperations: [
            { action: "modify", path: "src/generated/generatedPage.jsx", reason: "Render generated page." },
            { action: "modify", path: "src/generated/generatedPage.css", reason: "Style generated page." },
            { action: "add", path: "src/generated/catalogData.js", reason: "Store generated data." },
            { action: "modify", path: "src/generated/metadata.json", reason: "Record metadata." },
            { action: "delete", path: "src/generated/deprecatedGeneratedPage.jsx", reason: "Remove obsolete file." }
          ]
        }
      : orchestratedRequest;

  const sourceInstruction = cleanInstruction(request.sourceInstruction || request.objective);
  const instructionHash = crypto.createHash("sha256").update(sourceInstruction).digest("hex");
  const buildId = `build_${nanoid(10)}`;
  emit("build-start", `Build ${buildId} started for ${request.pageType}`, {
    buildId,
    pageType: request.pageType,
    topic: request.topic,
    instructionHash
  });
  emit("workspace-resolved", `Generated app workspace resolved: ${generatedSourceDir}`, {
    buildId,
    generatedSourceDir
  });
  await fs.ensureDir(generatedSourceDir);

  const operations = buildOperations(request, buildId, instructionHash);
  emit("operation-plan", `Preparing ${operations.length} generated-site file operations in dependency-safe order`, {
    buildId,
    operations: operations.map(({ action, path: filePath, reason }) => ({ action, path: filePath, reason }))
  });
  for (const operation of operations) {
    emit("file-operation-start", `${operation.action.toUpperCase()} ${operation.path}`, {
      buildId,
      action: operation.action,
      path: operation.path,
      reason: operation.reason
    });
    const operationResult = await applyOperation(operation);
    const detail =
      operation.action === "delete"
        ? operationResult.existedBefore
          ? "removed existing file"
          : "file was already absent"
        : `${operationResult.existedBefore ? "updated" : "created"} ${operationResult.bytesWritten} bytes`;
    emit("file-operation-done", `${operation.action.toUpperCase()} ${operation.path} complete: ${detail}`, {
      buildId,
      action: operation.action,
      path: operation.path,
      existedBefore: operationResult.existedBefore,
      bytesWritten: operationResult.bytesWritten
    });
  }
  emit("codegen-complete", `Build ${buildId} wrote ${operations.filter((operation) => operation.action !== "delete").length} active files`, {
    buildId,
    files: operations.filter((operation) => operation.action !== "delete").map((operation) => operation.path)
  });

  return {
    buildId,
    title: buildCommerceModel(request).brand,
    instructionHash,
    generatedAt: new Date().toISOString(),
    files: operations.filter((operation) => operation.action !== "delete").map((operation) => operation.path),
    fileOperations: operations.map(({ action, path: filePath, reason }) => ({ action, path: filePath, reason }))
  };
}
